defaults: &defaults
  working_directory: /go/src/github.com/gruntwork-io/cloud-nuke
  docker:
    - image: 087285199408.dkr.ecr.us-east-1.amazonaws.com/circle-ci-test-image-base:latest

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/cloud-nuke
      - restore_cache:
          keys:
            - dep-{{ checksum "Gopkg.lock" }}
      - run: dep ensure
      - save_cache:
          key: dep-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/gruntwork-io/cloud-nuke/vendor
      - persist_to_workspace:
          root: .
          paths: vendor

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/cloud-nuke
      - run:
          command: run-go-tests --circle-ci-2
          no_output_timeout: 20m

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/cloud-nuke
      - run: build-go-binaries --circle-ci-2 --app-name cloud-nuke --dest-path bin --ld-flags "-X main.VERSION=$CIRCLE_TAG"
      - persist_to_workspace:
          root: .
          paths: bin

  nuke_phx_devops:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/cloud-nuke
      - run: go run main.go aws --older-than 24h --exclude-region us-west-2 --force

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/cloud-nuke
      - run: upload-github-release-assets bin/*

workflows:
  version: 2
  build-and-test:
    jobs:
      - install_dependencies:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - install_dependencies
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
      - nuke_phx_devops:
          requires:
            - test
